kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - go version
  - go get ./...
  - go build ./...
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0
  - golangci-lint run --enable goconst --enable gocritic --enable misspell --enable prealloc --enable unconvert --enable unparam --enable gochecknoinits
  - go test -v -race -coverpkg=./... -coverprofile=coverage.txt

- name: coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov-token
    files:
      - coverage.txt